### ISSUE TITLE
v0.1.0 has no dist files

### ISSUE THREAD

**Issue by madeleineostoja** [cibernox/svelte-media#9]
The v0.1.0 package on NPM doesn't have any built files, just src by the look of it

<img width="213" alt="Screen Shot 2021-05-23 at 10 31 25 PM" src="https://user-images.githubusercontent.com/6374876/119256821-9f216380-bc16-11eb-9883-1d1d0b7eddfe.png">

**Comment by cibernox** [comment]
This should be fixed in 0.1.1

**Comment by madeleineostoja** [comment]
It has a dist, but now the path to the `types` is wrong, and there's no `main`, only `module`, which not all bundlers can resolve.
